import tensorflow as tf
import tensorflow.contrib.slim as slim

from utils import lrelu

import numpy as np


class Model(object):

    def __init__(self, mode='train_feature_generator', learning_rate=0.0003):

        self.mode = mode
        self.learning_rate = learning_rate
        self.hidden_repr_size = 128

    def feature_extractor(self, images, reuse=False, return_output=False):

        '''
        此为 Step 0 中的结构
        输入为图片
        输出为提取出的特征 128个节点 或  用于分类 10个节点
        原因在于：Step 0 和 Step 2 中其最后有分类的要求
                Step 1 中，时使用其提取出的特征训练 gan 来进行特征增强，不需要进行分类的任务
        '''

        '''
        Takes in input images and gives in output:
        1. logits, in the pretrain phase
        2. features, in the feature generation phase
        '''

        # 将 svhm (source data) 转为灰度图
        if images.get_shape()[3] == 3:
            images = tf.image.rgb_to_grayscale(images)

        # 网络结构构建
        with tf.variable_scope('feature_extractor', reuse=reuse):
            with slim.arg_scope([slim.conv2d], activation_fn=tf.nn.relu, padding='VALID'):
                net = slim.conv2d(images, 64, 5, scope='conv1')
                net = slim.max_pool2d(net, 2, stride=2, scope='pool1')
                net = slim.conv2d(net, 128, 5, scope='conv2')
                net = slim.max_pool2d(net, 2, stride=2, scope='pool2')
                net = tf.contrib.layers.flatten(net)
                net = slim.fully_connected(net, 1024, activation_fn=tf.nn.relu, scope='fc3')
                net = slim.fully_connected(net, self.hidden_repr_size, activation_fn=tf.tanh,
                                           scope='fc4')  # has to be tanh, as it's more welcomed by GANs

                # 因为再step 0 的最后 有C ，在 step 2的最后有C ，此时该net具有分类的作用
                if (self.mode == 'train_feature_extractor') or return_output:  # in the pretraining phase we need logits, in the feature generation phase we need features ,return featurn 再step2中值为true
                    net = slim.fully_connected(net, 10, activation_fn=None, scope='fc5')  # 此应该对应了十个分类
                print(slim.summary)
                return net

    def feature_generator(self, noise, labels, reuse=False):
        '''
        定义 gan 中 Generator 的网络结构
        论文使用cgan 的框架，所以需要在接受特征的同时也需要接受 lable
        '''

        '''
        Takes in input noise and labels, and
        generates f(z|y)
        '''


        inputs = tf.concat([noise, tf.cast(labels, tf.float32)], 1)

        #搭建网络
        with tf.variable_scope('feature_generator', reuse=reuse):
            with slim.arg_scope([slim.fully_connected], weights_initializer=tf.contrib.layers.xavier_initializer(),
                                biases_initializer=tf.constant_initializer(0.0)):
                with slim.arg_scope([slim.batch_norm], decay=0.95, center=True, scale=True,
                                    activation_fn=tf.nn.relu, is_training=(self.mode == 'train_feature_generator')):
                    net = slim.fully_connected(inputs, 1024, activation_fn=tf.nn.relu, scope='sgen_fc1')
                    net = slim.batch_norm(net, scope='sgen_bn1')
                    net = slim.dropout(net, 0.5)  # dropout needs to be always on, do not include "is_training"
                    net = slim.fully_connected(net, 1024, activation_fn=tf.nn.relu, scope='sgen_fc2')
                    net = slim.batch_norm(net, scope='sgen_bn2')
                    net = slim.dropout(net, 0.5) #设置dropout层，防止过拟合
                    net = slim.fully_connected(net, self.hidden_repr_size, activation_fn=tf.tanh, scope='sgen_feat')
                    return net

    def feature_discriminator(self , features, labels, reuse=False):


        '''
        Used in Step 1 to discriminate between
        real and generated features. Takes in
        input features and associated labels and
        has to discriminate whether they are real
        or generated by feature_generator
        '''

        '''
        Step 1 中的 Discriminate
        用于区分产生的特征是真实的，还是从generator中产生的
        输入为 lable 和 特征
        '''
        inputs = tf.concat([features, tf.cast(labels, tf.float32)], 1)

        with tf.variable_scope('feature_discriminator', reuse=reuse):
            with slim.arg_scope([slim.fully_connected], weights_initializer=tf.contrib.layers.xavier_initializer(),
                                biases_initializer=tf.constant_initializer(0.0)):
                net = slim.fully_connected(inputs, 1024, activation_fn=tf.nn.relu, scope='sdisc_fc1')
                net = slim.fully_connected(net, 1, activation_fn=tf.sigmoid, scope='sdisc_prob')
                return net

    def feature_discriminator_DIFA(self, features, reuse=False):
        '''
        Used in Step 2 to discriminate between
        source and target features. Takes in input
        features and has to discriminate whether
        they are from S or from the encoder we are
        training.
        '''

        '''
        Step 2 中的 Discriminate 
        用于区分他们是从 Step1中的Generator中生成的feature 还是由E_1 encode 出的feature 
        输入为 feature
        
        '''

        with tf.variable_scope('feature_discriminator_DIFA', reuse=reuse):
            with slim.arg_scope([slim.fully_connected], weights_initializer=tf.contrib.layers.xavier_initializer(),
                                biases_initializer=tf.constant_initializer(0.0)):
                net = slim.fully_connected(features, 1024, activation_fn=lrelu, scope='sdisc_DIFA_fc1')
                net = slim.fully_connected(net, 1, activation_fn=tf.sigmoid, scope='sdisc_DIFA_prob')
                return net

    # 根据 self.mode 构建模型
    def build_model(self):

        if self.mode == 'train_feature_extractor':

            #################################################################################################################
            # Step 0: training a classifier to classify well some images (source images, if using it for domain adaptation) #
            #################################################################################################################

            # placeholder，占位符，在tensorflow中类似于函数参数，运行时必须传入值。 None表示数据量不确定
            self.images = tf.placeholder(tf.float32, [None, 32, 32, 3], 'images')
            self.labels = tf.placeholder(tf.int64, [None], 'labels')

            # extracting logits through feature_extractor (C(E_S) in the paper)
            # 获取 feature_extractor 产生的网络
            self.logits = self.feature_extractor(self.images)

            #指定loss（交叉熵）和 优化器（Adam）
            self.loss = slim.losses.sparse_softmax_cross_entropy(self.logits, self.labels)
            self.optimizer = tf.train.AdamOptimizer(self.learning_rate)

            # loss and optimizer
            # 构建 train_op ,其作用为根据Loss 和 优化器 来更新参数 an operation that computes the loss and applies the gradients
            self.train_op = slim.learning.create_train_op(self.loss, self.optimizer)

            # 寻找出最大的值作为预测，1代表方向
            self.pred = tf.argmax(self.logits, 1)
            # correct_pred 为是否成功匹配
            self.correct_pred = tf.equal(self.pred, self.labels)
            #准确率 reduce_mean在只有一个参数情况下计算所有元素均值
            self.accuracy = tf.reduce_mean(tf.cast(self.correct_pred, tf.float32))

            # summary
            loss_summary = tf.summary.scalar('classification_loss', self.loss)
            src_accuracy_summary = tf.summary.scalar('accuracy', self.accuracy)
            self.summary_op = tf.summary.merge([loss_summary, src_accuracy_summary])

        elif self.mode == 'train_feature_generator':

            #######################################################################################################################
            # Step 1: training a feature generator to generate realistic features conditioning on a noise vector and a label code #
            #######################################################################################################################

            # placeholder，占位符，在tensorflow中类似于函数参数，运行时必须传入值。 None表示数据量不确定
            self.images = tf.placeholder(tf.float32, [None, 32, 32, 3], 'images')
            self.noise = tf.placeholder(tf.float32, [None, 100], 'noise')
            self.labels = tf.placeholder(tf.int64, [None, 10], 'labels')

            # extracting features associated to our images through extractor (E_S in the paper)
            # 需要训练好 feature_extractor ，使用feature_extractor生成真实图片对应的 real_features
            self.real_features = self.feature_extractor(self.images)

            # features generated by feature_generator (S in the paper)
            # 由 feature_generator 生成的 feature
            self.gen_features = self.feature_generator(self.noise, self.labels)

            # In the following:
            #
            # 'real': related to features extracted from images.
            # 'fake': related to generated features.
            # The minimax game is solved in the Least Squares GAN framework.
            # Ones are related to real features, zeros to generated features. Generator is trained by flipping labels.

            # feature_discriminator 构建的 Discriminator
            self.logits_real = self.feature_discriminator(self.real_features, self.labels)
            self.logits_fake = self.feature_discriminator(self.gen_features, self.labels, reuse=True)

            # Discriminator 在 real feature 上的loss 和 在 fake feature上的loss
            self.d_loss_real = tf.reduce_mean(tf.square(self.logits_real - tf.ones_like(self.logits_real)))
            self.d_loss_fake = tf.reduce_mean(tf.square(self.logits_fake - tf.zeros_like(self.logits_fake)))
            # Discriminator 总 loss
            self.d_loss = self.d_loss_real + self.d_loss_fake

            # Generator 的 loss
            self.g_loss = tf.reduce_mean(
                tf.square(self.logits_fake - tf.ones_like(self.logits_fake)))  # flipping labels

            # Discriminator 和 Generator 的优化器
            self.d_optimizer = tf.train.AdamOptimizer(self.learning_rate)
            self.g_optimizer = tf.train.AdamOptimizer(self.learning_rate)

            #tf.trainable_variables() 这个函数可以也仅可以查看可训练的变量
            t_vars = tf.trainable_variables()
            # 查看 feature_discriminator scope中的可训练变量
            d_vars = [var for var in t_vars if 'feature_discriminator' in var.name]
            # 查看 feature_generator scope中的可训练变量
            g_vars = [var for var in t_vars if 'feature_generator' in var.name]

            with tf.variable_scope('train_op', reuse=False):

                # 构建 train_op ,其作用为根据Loss 和 优化器 来更新参数 an operation that computes the loss and applies the gradients
                # 关于 variables_to_train 参数，指定训练参数 an optional list of variables to train. If None, it will default to all tf.compat.v1.trainable_variables().
                # training feature_discriminator to classify real features as ones and fake features as zeros.
                self.d_train_op = slim.learning.create_train_op(self.d_loss, self.d_optimizer,variables_to_train=d_vars)

                # training feature_generator to make feature_discriminator classify fake features as ones, i.e. to generate more realistic features.
                self.g_train_op = slim.learning.create_train_op(self.g_loss, self.g_optimizer,variables_to_train=g_vars)

            # summary
            d_loss_summary = tf.summary.scalar('d_loss', self.d_loss)
            g_loss_summary = tf.summary.scalar('g_loss', self.g_loss)
            self.summary_op = tf.summary.merge([d_loss_summary, g_loss_summary])

            for var in tf.trainable_variables():
                tf.summary.histogram(var.op.name, var)

        elif self.mode == 'train_DIFA':

            ########################################################################################################
            # Step 2: training a feature extractor to map both source and target samples in the same feature space #
            ########################################################################################################

            # placeholder，占位符，在tensorflow中类似于函数参数，运行时必须传入值。 None表示数据量不确定
            self.noise = tf.placeholder(tf.float32, [None, 100], 'noise')
            self.labels = tf.placeholder(tf.float32, [None, 10], 'labels')  # to generate features with S
            self.src_images = tf.placeholder(tf.float32, [None, 32, 32, 3], 'svhn_images')
            self.trg_images = tf.placeholder(tf.float32, [None, 32, 32, 1], 'mnist_images')


            self.trg_labels = self.feature_extractor(self.trg_images, return_output=True)

            # 用于测试
            self.trg_labels_gt = tf.placeholder(tf.int64, [None],
'mnist_labels_for_testing')  # ground truth for target, used for testing
            self.trg_pred = tf.argmax(self.trg_labels, 1)
            self.trg_correct_pred = tf.equal(self.trg_pred, self.trg_labels_gt)
            self.trg_accuracy = tf.reduce_mean(tf.cast(self.trg_correct_pred, tf.float32))

            #合并 source images 和 target images
            self.images = tf.concat([tf.image.rgb_to_grayscale(self.src_images), self.trg_images], 0)

            # feature_generator 生成的网络，即S
            self.features_from_S = self.feature_generator(self.noise, self.labels)
            # feature_extractor 生成的网络，即E
            self.features_from_E = self.feature_extractor(self.images, reuse=True)


            self.logits_real = self.feature_discriminator_DIFA(self.features_from_S)
            self.logits_fake = self.feature_discriminator_DIFA(self.features_from_E, reuse=True)

            # Discriminator 在 real feature 上的loss 和 在 fake feature上的loss
            self.d_loss_real = tf.reduce_mean(tf.square(self.logits_real - tf.ones_like(self.logits_real)))
            self.d_loss_fake = tf.reduce_mean(tf.square(self.logits_fake - tf.zeros_like(self.logits_fake)))
            # Discriminator 总 loss
            self.d_loss = self.d_loss_real + self.d_loss_fake

            # Encoder loss
            self.e_loss = tf.reduce_mean(tf.square(self.logits_fake - tf.ones_like(self.logits_fake)))

            #Discriminator 和 Encoder 的 Optimizers
            self.d_optimizer = tf.train.AdamOptimizer(self.learning_rate)
            self.e_optimizer = tf.train.AdamOptimizer(self.learning_rate)

            t_vars = tf.trainable_variables()
            # 查看 feature_extractor scope中的可训练变量
            e_vars = [var for var in t_vars if 'feature_extractor' in var.name]
            # 查看 feature_discriminator_DIFA scope中的可训练变量
            d_vars = [var for var in t_vars if 'feature_discriminator_DIFA' in var.name]

            # train op
            with tf.variable_scope('training_op', reuse=False):
                # 构建 Si Encoder 和 D_2 Discriminator train_op
                self.e_train_op = slim.learning.create_train_op(self.e_loss, self.e_optimizer,variables_to_train=e_vars)
                self.d_train_op = slim.learning.create_train_op(self.d_loss, self.d_optimizer,variables_to_train=d_vars)

            # summary op
            e_loss_summary = tf.summary.scalar('G_loss', self.e_loss)
            d_loss_summary = tf.summary.scalar('D_loss', self.d_loss)
            self.summary_op = tf.summary.merge([e_loss_summary, d_loss_summary])

            for var in tf.trainable_variables():
                tf.summary.histogram(var.op.name, var)

        else:
            raise Exception('Unknown mode.')
